# Generated by Django 4.1.3 on 2022-11-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='galeria_proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=100)),
                ('descripción', models.CharField(max_length=500)),
            ],
        ),
    ]
