# Generated by Django 4.1.3 on 2022-11-14 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cubicoprojectapp', '0005_alter_galeria_proyectos_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria_proyectos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galeria_proyectos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
