# Generated by Django 4.1.3 on 2022-11-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubicoprojectapp', '0006_galeria_proyectos_created_galeria_proyectos_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria_proyectos',
            name='created',
        ),
        migrations.RemoveField(
            model_name='galeria_proyectos',
            name='updated',
        ),
    ]
