# Generated by Django 4.1.3 on 2022-11-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubicoprojectapp', '0008_galeria_proyectos_created_galeria_proyectos_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='galeria_proyectos',
        ),
    ]
