# Generated by Django 4.1.3 on 2022-11-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cubicoprojectapp', '0009_delete_galeria_proyectos'),
    ]

    operations = [
        migrations.CreateModel(
            name='galeria_proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen del proyecto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('descripcion', models.CharField(max_length=500, verbose_name='descripción general')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
