# Generated by Django 4.1.3 on 2022-11-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubicoprojectapp', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cubico_dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('telefono', models.CharField(max_length=500, verbose_name='descripción general')),
            ],
        ),
        migrations.AlterField(
            model_name='galeria_proyectos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='galeria_proyectos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modificación'),
        ),
    ]
