# Generated by Django 4.1.3 on 2022-11-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubicoprojectapp', '0011_cubico_dato_alter_galeria_proyectos_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cubico_dato',
        ),
    ]
