# Generated by Django 4.1.3 on 2022-11-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubicoprojectapp', '0013_cubico_redes_dato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cubico_redes_dato',
        ),
    ]
