# Generated by Django 4.1.3 on 2023-09-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='contratos',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='planos',
            field=models.FileField(blank=True, null=True, upload_to='planos/'),
        ),
    ]
