# Generated by Django 4.1.3 on 2023-09-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_plano_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='archivo',
            new_name='archivo2',
        ),
        migrations.RenameField(
            model_name='plano',
            old_name='archivo',
            new_name='archivo1',
        ),
    ]
