# Generated by Django 4.1.3 on 2023-09-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_rename_archivo_contrato_archivo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
