# Generated by Django 4.1.3 on 2023-09-12 22:13

from django.db import migrations, models
import login_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_remove_plano_proyecto_delete_contrato_delete_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=login_app.models.archivo_ruta)),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='contratos',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='planos',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='contratos',
            field=models.ManyToManyField(blank=True, related_name='proyectos_contratos', to='login_app.archivo'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='planos',
            field=models.ManyToManyField(blank=True, related_name='proyectos_planos', to='login_app.archivo'),
        ),
    ]
