# Generated by Django 4.1.3 on 2023-09-13 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_archivo_remove_proyecto_contratos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_app.proyecto'),
            preserve_default=False,
        ),
    ]
