# Generated by Django 4.1.3 on 2023-09-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_archivo_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='proyecto',
        ),
    ]
