# Generated by Django 4.1.3 on 2023-09-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0009_remove_archivo_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='es_plano',
            field=models.BooleanField(default=False),
        ),
    ]
