# Generated by Django 4.1.3 on 2023-09-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0010_archivo_es_plano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='es_plano',
        ),
    ]
