# Generated by Django 4.1.3 on 2023-09-19 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0011_remove_archivo_es_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='login_app.proyecto'),
            preserve_default=False,
        ),
    ]
